-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrQRNueqWmDhu1TXh
P2+Wmg/7Czdw01u112kTVZ9yUdmgCgYIKoZIzj0DAQehRANCAARIRkGucBGMJQu+
EdhkAjhQL4sW5Qvm4nX0RH/lBhBVONUD8UvAS1eHKFNFMd+fCaxaWETwpMViz660
NchZKWof
-----END PRIVATE KEY-----